/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bisanti.util;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import org.bisanti.swingx.JTablePlus;

/**
 *
 * @author Jason Bisanti
 */
public class Demo extends javax.swing.JFrame
{

    /**
     * Creates new form Demo
     */
    public Demo()
    {
        initComponents();
        
        this.jTablePlus1.addPropertyChangeListener(JTablePlus.COLUMN_SORTED, new PropertyChangeListener()
        {
            @Override
            public void propertyChange(PropertyChangeEvent evt)
            {
                sortLabel.setText(evt.getNewValue().toString());
            }
        });
        
        this.jTablePlus1.addPropertyChangeListener(JTablePlus.SORT_ORDER, new PropertyChangeListener()
        {
            @Override
            public void propertyChange(PropertyChangeEvent evt)
            {
                sortOrderLabel.setText(evt.getNewValue().toString());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlus1 = new org.bisanti.swingx.JTablePlus();
        jLabel1 = new javax.swing.JLabel();
        sortLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sortOrderLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePlus1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"John", "Doe",  new Boolean(true),  new Integer(35)},
                {"Jane", "Doe", null,  new Integer(33)},
                {"Elvis ", "Presley",  new Boolean(true),  new Integer(100)},
                {"Queen", "Victoria", null,  new Integer(150)}
            },
            new String []
            {
                "First Name", "Last Name", "Male", "Age"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePlus1);

        jLabel1.setText("Sorted Column:");

        sortLabel.setText("-1");

        jLabel2.setText("Sort Order:");

        sortOrderLabel.setText("UNSORTED");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortOrderLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sortLabel)
                    .addComponent(jLabel2)
                    .addComponent(sortOrderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Demo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.bisanti.swingx.JTablePlus jTablePlus1;
    private javax.swing.JLabel sortLabel;
    private javax.swing.JLabel sortOrderLabel;
    // End of variables declaration//GEN-END:variables
}
