/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bisanti.swingx;

import java.awt.Component;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import org.bisanti.util.Util;

/**
 *
 * @author Jason Bisanti
 */
public class ColumnFilterPanel extends javax.swing.JPanel
{
    
    public static enum FILTER
    {
        EQUALS("equals", false),
        CONTAINS("contains", true),
        LESS_THAN("less than", false),
        GREATER_THAN("greater than", false),
        LESS_THAN_EQUAL_TO("less than or equal to", false),
        GREATER_THAN_EQUAL_TO("greater than or equal to", false),
        DOES_NOT_EQUAL("does not equal", false),
        DOES_NOT_CONTAIN("does not contain", true);
        
        private final String text;
        
        private final boolean stringOnlyFilter;
        
        FILTER(String text, boolean stringOnlyFilter)
        {
            this.text = text;
            this.stringOnlyFilter = stringOnlyFilter;
        }
        
        public String getText()
        {
            return this.text;
        }
        
        public boolean isStringOnlyFilter()
        {
            return this.stringOnlyFilter;
        }
    }
    
    public static final String AND_BUTTON = "columnFilterAndButton";
    
    public static final String OR_BUTTON = "columnFilterOrButton";
    
    private TableColumnModel model;
    
    /**
     * Creates new form ColumnFilterPanel
     */
    public ColumnFilterPanel()
    {
        initComponents();
        
        this.columnComboBox.setRenderer(new DefaultListCellRenderer()
        {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus)
            {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if(value instanceof TableColumn)
                {
                    super.setText(((TableColumn)value).getIdentifier().toString());
                }
                return this;
            }            
        });
        
        this.filterComboBox.setRenderer(new DefaultListCellRenderer()
        {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus)
            {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if(value instanceof FILTER)
                {
                    super.setText(((FILTER)value).text);
                }
                return this;
            }                   
        });
    }
    
    public ColumnFilterPanel(TableColumnModel model, TableColumn column)
    {
        this.model = model;
        TableColumn[] columns = Util.asList(model.getColumns()).toArray(new TableColumn[model.getColumnCount()]);
        this.columnComboBox.setModel(new DefaultComboBoxModel(columns));
        if(column != null)
        {
            this.columnComboBox.setSelectedItem(column);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        columnComboBox = new javax.swing.JComboBox();
        filterComboBox = new javax.swing.JComboBox();
        textField = new javax.swing.JTextField();
        andButton = new javax.swing.JToggleButton();
        orButton = new javax.swing.JToggleButton();

        jLabel1.setText("Column");

        columnComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filterComboBox.setModel(new javax.swing.DefaultComboBoxModel(FILTER.values()));

        andButton.setText("And");
        andButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                andButtonActionPerformed(evt);
            }
        });

        orButton.setText("Or");
        orButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                orButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(columnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(andButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(columnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andButton)
                    .addComponent(orButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void andButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_andButtonActionPerformed
    {//GEN-HEADEREND:event_andButtonActionPerformed
        boolean selected = this.andButton.isSelected();
        super.firePropertyChange(AND_BUTTON, !selected, selected);
    }//GEN-LAST:event_andButtonActionPerformed

    private void orButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_orButtonActionPerformed
    {//GEN-HEADEREND:event_orButtonActionPerformed
        boolean selected = this.andButton.isSelected();
        super.firePropertyChange(OR_BUTTON, !selected, selected);
    }//GEN-LAST:event_orButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton andButton;
    private javax.swing.JComboBox columnComboBox;
    private javax.swing.JComboBox filterComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton orButton;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
