/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bisanti.swingx;

import java.awt.GridBagConstraints;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.List;
import org.bisanti.util.StringUtil;

/**
 *
 * @author Jason Bisanti
 */
public class ColumnFilterPopup extends javax.swing.JFrame
{
    private List<ColumnFilterPanel> filters = new ArrayList<ColumnFilterPanel>();

    /**
     * Creates new form ColumnFilterPopup
     */
    public ColumnFilterPopup()
    {
        initComponents();
        this.filters.add(this.columnFilterPanel1);
        this.columnFilterPanel1.addPropertyChangeListener(this.createPCL());
    }
    
    private PropertyChangeListener createPCL()
    {
        return new PropertyChangeListener()
        {
            @Override
            public void propertyChange(PropertyChangeEvent evt)
            {                
                if(StringUtil.equals(evt.getPropertyName(), 
                        ColumnFilterPanel.AND_BUTTON, 
                        ColumnFilterPanel.OR_BUTTON))
                {
                    Boolean selected = Boolean.valueOf(evt.getNewValue().toString());
                    
                    if(selected)
                    {
                        ColumnFilterPanel cfp = new ColumnFilterPanel();
                        cfp.addPropertyChangeListener(createPCL());
                        GridBagConstraints newGBC = new GridBagConstraints();
                        newGBC.gridx = 0;
                        newGBC.gridy = filters.size();
                        panel.add(cfp, newGBC);
                        filters.add(cfp);
                    }
                    else
                    {
                        int index = filters.indexOf(evt.getSource());
                        List<ColumnFilterPanel> remove = new ArrayList<ColumnFilterPanel>();
                        for(int i=index + 1; i<filters.size(); i++)
                        {
                            ColumnFilterPanel cfp = filters.get(i);
                            panel.remove(cfp);
                            remove.add(cfp);
                        }
                        filters.removeAll(remove);
                    }
                    revalidate();
                    repaint();
                }
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        scrollPane = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        columnFilterPanel1 = new org.bisanti.swingx.ColumnFilterPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panel.add(columnFilterPanel1, gridBagConstraints);

        scrollPane.setViewportView(panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.bisanti.swingx.ColumnFilterPanel columnFilterPanel1;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables


}
