/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.bisanti.swingx;

import javax.swing.text.JTextComponent;
import org.bisanti.util.StringUtil;

/**
 *
 * @author Jason Bisanti
 */
class FindFrame extends javax.swing.JFrame
{
    private int caretPosition;
    
    private JTextComponent textComponent;

    /**
     * Creates new form FindFrame
     */
    FindFrame()
    {
        initComponents();
        this.commentLabel.setVisible(false);
    }

    int getCaretPosition()
    {
        return caretPosition;
    }

    void setCaretPosition(int caretPosition)
    {
        this.caretPosition = caretPosition;
    }

    JTextComponent getTextComponent()
    {
        return textComponent;
    }

    void setTextComponent(JTextComponent textComponent)
    {
        this.textComponent = textComponent;
    }
    
    void find(boolean forward)
    {       
        String toSearch = StringUtil.nonNull(this.textComponent.getText(), false);        
        String toFind = StringUtil.nonNull(this.findTextField.getText(), false);
        final boolean matchCase = this.caseCheckBox.isSelected();
        
        final int index;
        if(forward)
        {
            index = StringUtil.indexOf(matchCase, toSearch.substring(this.caretPosition), toFind);
            this.select(index, toFind);
        }
        else
        {
            index = StringUtil.lastIndexOf(matchCase, toSearch.substring(0, this.caretPosition), toFind);
            this.select(index, toFind);
        }
        this.caretPosition = index;
        
        if(this.caretPosition < 0)
        {
            this.commentLabel.setVisible(true);
            this.commentLabel.setText("No more instances found. Search will resume from " + (forward ? "beginning" : "end"));
            this.caretPosition = forward ? 0 : toSearch.length() - 1;
        }
    }
    
    private void select(int index, String s)
    {
        if(index > -1)
        {
            this.textComponent.select(index, index + s.length());
        }
    }
    
    @Override
    public void requestFocus()
    {
        super.requestFocus();
        this.findTextField.requestFocus();
    }
    
    @Override
    public void dispose()
    {
        super.dispose();
        this.textComponent = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        caseCheckBox = new javax.swing.JCheckBox();
        findTextField = new javax.swing.JTextField();
        commentLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Find Text");

        caseCheckBox.setText("Match Case");

        commentLabel.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        commentLabel.setText("No more instances found. Search will start from beginning/end");

        jButton1.setText("< Previous");

        jButton2.setText("Next >");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(findTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caseCheckBox))
                            .addComponent(commentLabel))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(caseCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox caseCheckBox;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JTextField findTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
