package org.bisanti.swingx;

import javax.swing.text.JTextComponent;
import org.bisanti.util.StringUtil;

/**
 * <i>
 * Written and authored by Jason Bisanti. Free to use and reproduce, but please
 * keep my name as the original author!
 * <br><br></i>
 * @author Jason Bisanti
 */
class FindFrame extends javax.swing.JFrame
{
    private int caretPosition;
    
    private JTextComponent textComponent;

    /**
     * Creates new form FindFrame
     */
    FindFrame()
    {
        super("Find");
        initComponents();
        this.commentLabel.setVisible(false);
    }

    int getCaretPosition()
    {
        return caretPosition;
    }

    void setCaretPosition(int caretPosition)
    {
        this.caretPosition = caretPosition;
    }

    JTextComponent getTextComponent()
    {
        return textComponent;
    }

    void setTextComponent(JTextComponent textComponent)
    {
        this.textComponent = textComponent;
    }
    
    String getText()
    {
        return this.findTextField.getText();
    }
    
    void setText(String text)
    {
        this.findTextField.setText(text);
    }
    
    void find(boolean forward)
    {       
        this.commentLabel.setVisible(false);
        
        String toSearch = StringUtil.nonNull(this.textComponent.getText(), false);        
        String toFind = StringUtil.nonNull(this.findTextField.getText(), false);
        final boolean matchCase = this.caseCheckBox.isSelected();
        
        final int index;
        if(forward)
        {
            index = StringUtil.indexOf(matchCase, this.caretPosition, toSearch, toFind);
            this.select(index, toFind);
        }
        else
        {
            index = StringUtil.lastIndexOf(matchCase, this.caretPosition, toSearch, toFind);
            this.select(index, toFind);
        }
        
        if(index < 0)
        {
            this.commentLabel.setVisible(true);
            this.commentLabel.setText("No more instances found. Search will resume from " + (forward ? "beginning." : "end."));
            this.caretPosition = forward ? 0 : toSearch.length() - 1;
        }
        else
        {
            this.caretPosition = forward ? index + toFind.length() : index;
        }
    }
    
    private void select(int index, String s)
    {
        if(index > -1)
        {
            this.textComponent.grabFocus();
            this.textComponent.select(index, index + s.length());
        }
    }
    
    @Override
    public void requestFocus()
    {
        super.requestFocus();
        this.findTextField.requestFocus();
    }
    
    @Override
    public void dispose()
    {
        super.dispose();
        this.textComponent = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        caseCheckBox = new javax.swing.JCheckBox();
        findTextField = new javax.swing.JTextField();
        commentLabel = new javax.swing.JLabel();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Find Text");

        caseCheckBox.setText("Match Case");

        commentLabel.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        commentLabel.setText("No more instances found. Search will start from beginning/end");

        previousButton.setText("< Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                previousButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next >");
        nextButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(findTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caseCheckBox))
                            .addComponent(commentLabel))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previousButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(caseCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousButton)
                    .addComponent(nextButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_previousButtonActionPerformed
    {//GEN-HEADEREND:event_previousButtonActionPerformed
        this.find(false);
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nextButtonActionPerformed
    {//GEN-HEADEREND:event_nextButtonActionPerformed
        this.find(true);
    }//GEN-LAST:event_nextButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox caseCheckBox;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JTextField findTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    // End of variables declaration//GEN-END:variables
}
