package org.bisanti.swingx;

import javax.swing.text.html.HTMLEditorKit;

/**
 * <i>
 * Written and authored by Jason Bisanti. Free to use and reproduce, but please
 * keep my name as the original author!
 * <br><br></i>
 * @author Jason Bisanti
 */
public class JTablePlusHelp extends javax.swing.JFrame
{
    /**
     * Creates new form JTablePlusHelp
     */
    public JTablePlusHelp()
    {
        super("Table Help");
        initComponents();
        String br = "<br><br>";
        this.textPane.setEditorKit(new HTMLEditorKit());
        StringBuilder sb = new StringBuilder("<h3>Sorting</h3>");
        sb.append("Left-clicking on a column header once will sort rows based on that column's value for each row in ascending order. A subsequent left-click will sort the rows in descending order. ");
        sb.append(br);
        sb.append("To unsort the column, right-click any column and select the 'Unsort/Unfilter' option. Only one column can be sorted at a time.");
        sb.append("<h3>Filtering</h3>");
        sb.append("The 'Filter...' option is available by either right-clicking on a column header or left-clicking on the menu button in the top-right corner of the table. ");
        sb.append("This menu option displays a popup that allows you to only display rows whose cell values meet a specific criteria. ");
        sb.append(br);
        sb.append("Table cells that do not display any text use a textual representation of that value for comparison. ");
        sb.append("For example, a selected check box would be represented as 'true' and an unselected check box would be represented as 'false'.");
        sb.append(br);
        sb.append("To remove all filters, right-click on a column header or left-click the button in the top-right corner of the table and select 'Unsort/Unfilter'.");
        sb.append("<h3>Hiding Columns</h3>");
        sb.append("To hide a column, right-click the column header and select the 'Hide' option from the menu. ");
        sb.append(br);
        sb.append("To show (and hide) the column, click the menu button in the top-right corner of the table and select the appropriate check box from the menu.");
        sb.append("<h3>Moving Columns</h3>");
        sb.append("To move a column, hold down the left mouse button on the column's header, drag it to the desired location, and release the left mouse button.");
        
        this.textPane.setText(sb.toString());
        this.textPane.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane2 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textPane.setEditable(false);
        jScrollPane2.setViewportView(textPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables
}
